TL_MIS, UTL_MIS をpytestで使えるようにした
ut-issl/python-wings-interface pull request #17
Opened 2022-04-04 09:44 UTC by chutaro

## 概要
TL_MIS, UTL_MIS をpytestで使えるようにした

## Issue
- https://github.com/ut-issl/c2a-core/issues/138

## 詳細
詳しく

## 検証結果
手元で既存のpytestが全て通った。send_tl_mis, send_utl_mis については以下のブランチでpytestを作り動作確認した。
- https://github.com/ut-issl/c2a-core/pull/307

2022-04-04 16:37 UTC, meltingrabbit commented on isslwings/operation.py
> +    def _send_cmd(self, command: dict) -> None:
[IMO] _send_cmd の引数に `execType` と `execTime` とればよさそう？
 timeはデフォルト引数0にしてしまえば，RTの場合は引数なしでもpythonならいけるし

2022-04-05 01:18 UTC, chutaro commented on isslwings/operation.py
> +    def _send_cmd(self, command: dict) -> None:
exectime が RT,BL,TLだとint, UTLだとfloat なので，同じ引数として取るとちょっとキモいなと思ったんですよね。（全部floatで取ってからintのやつだけキャストとかになっちゃうので）

2022-04-05 16:52 UTC, meltingrabbit commented on isslwings/operation.py
> +    def _send_cmd(self, command: dict) -> None:
たしかに～

2022-04-05 16:53 UTC, meltingrabbit approved these changes
良さそうです．

- https://github.com/ut-issl/c2a-core/pull/307 

との依存があって，互換性無くなる場合，バージョンあげが必要なので，どこかで通話しながらマージ作業しましょうか．

2022-04-06 00:25 UTC, meltingrabbit commented
- https://github.com/ut-issl/c2a-core/pull/307 ではまだpytestが追加されてないので，まだマージしない
- そのtestがcoreに追加されるタイミングでマージする

2022-04-06 00:26 UTC, meltingrabbit requested changes
- https://github.com/ut-issl/c2a-core/pull/307 ではまだpytestが追加されてないので，まだマージしない
- そのtestがcoreに追加されるタイミングでマージする

2022-04-25 06:20 UTC, meltingrabbit approved these changes

2022-04-25 06:29 UTC, merged

2022-04-25 06:35 UTC, chutaro commented
リリース打ちました
https://github.com/ut-issl/python-wings-interface/releases/tag/v1.2.0